- pkg/common/metrics/metrics.go
- pkg/controllers/member/endpointslice/controller_integration_test.go
- pkg/controllers/member/internalserviceexport/controller.go
- pkg/controllers/member/internalserviceexport/controller_integration_test.go
- pkg/controllers/member/internalserviceexport/controller_test.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller_test.go
/kind bug
This PR fixes the following issues:
* Use resource versions rather than generations to track last seen/observed data in service exports, as Kubernetes does not track service generations
* Address a corner racing condition which may lead the controller to unexport services unexpectedly.
It also fixes a minor issue that may lead to flaky endpointSlice controller integration tests.
N/A
- [N/A] includes documentation
[x] unit tests
[x] integration tests
> fix: service export metrics + corner cases

- .github/workflows/commit-lint.yml
/kind regression
upgrade the pr-title-checker to fix the 1.3.1 issue
```
/home/runner/work/_actions/thehanimo/pr-title-checker/v1.3.1/index.js:110
if (alwaysPassCI) {
^
ReferenceError: alwaysPassCI is not defined
at removeLabel (/home/runner/work/_actions/thehanimo/pr-title-checker/v1.3.1/index.js:110:1)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
> chore: fix github action commit-lint

- test/scripts/bootstrap.sh
/kind bug
/kind failing-test
The fleet version should match the one defined in the go module.
Fixes #
The fix cannot be tested until we merge the PR.
> fix: fix the e2e tests

- cmd/mcs-controller-manager/main.go
- cmd/member-net-controller-manager/main.go
/kind bug
This PR adds the cluster API to the scheduler in related controllers so that they can function when v1beta1 API is enabled.
- [N/A] includes documentation
- [N/A] adds unit tests
> fix: add cluster API to the scheme in related controllers

- .github/workflows/build-publish-mcr.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/go.yml
- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
- .github/workflows/unit-integration-tests.yml
- Makefile
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- go.mod
/kind bug
scan image failed
https://github.com/Azure/fleet/actions/runs/8997697599/job/24716356414
hubagent (gobinary)
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬────────────────────────────────────────────────────┐
│ Library │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │ Title │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼────────────────────────────────────────────────────┤
│ stdlib │ CVE-2023-[45](https://github.com/Azure/fleet/actions/runs/8997697599/job/24716356414#step:8:46)288 │ HIGH │ fixed │ 1.20.14 │ 1.21.9, 1.22.2 │ golang: net/http, …
> fix: upgrade golang version to 1.22.2 for CVE-2023-45288

- .github/workflows/build-publish-mcr.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/go.yml
- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
- .github/workflows/unit-integration-tests.yml
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- go.mod
- go.sum
fix CVE-2024-24788
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-2[47](https://github.com/Azure/fleet/actions/runs/9038604706/job/24840052636#step:8:48)88 │ HIGH     │ fixed  │ 1.22.2            │ 1.22.3        │ golang: net: malformed DNS message can cause infinite loop │
│         │                │          │        │                   │ …
> fix: upgrade go version to 1.22.3 for CVE-2024-24788 

- charts/mcs-controller-manager/values.yaml
- charts/member-net-controller-manager/values.yaml
- config/crd/bases/networking.fleet.azure.com_endpointsliceexports.yaml
- config/crd/bases/networking.fleet.azure.com_endpointsliceimports.yaml
- config/crd/bases/networking.fleet.azure.com_internalserviceexports.yaml
- config/crd/bases/networking.fleet.azure.com_internalserviceimports.yaml
- config/crd/bases/networking.fleet.azure.com_multiclusterservices.yaml
- config/crd/bases/networking.fleet.azure.com_serviceexports.yaml
- config/crd/bases/networking.fleet.azure.com_serviceimports.yaml
- config/rbac/role.yaml
- examples/getting-started/charts/hub/templates/rbac.yaml
- pkg/controllers/member/internalmembercluster/v1beta1/controller_v1beta1.go
- test/e2e/e2e_test.go
- test/e2e/join_test.go
- test/scripts/bootstrap.sh
/kind test
- Test v1beta1 imc instead of v1alpha1
- Use v1beta1 fleet api by default
- Regenerate the CRD by using new controller-gen
Fixes #
Validated the changes in my local
```
Ran 22 of 22 Specs in 604.438 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestE2E (604.44s)
PASS
ok      go.goms.io/fleet-networking/test/e2e    604.457s
```
> test: update the e2e test to use v1beta1 imc

- api/v1alpha1/trafficmanagerbackend_types.go
- api/v1alpha1/trafficmanagerprofile_types.go
- config/crd/bases/networking.fleet.azure.com_trafficmanagerbackends.yaml
- config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml
/kind api-change
In order to reduce the Azure update call, we need to know the default value of the profile configuration when comparing the profile spec with the azure profile resource.
It's better to define them in the API itself.
Fixes #
> interface: add the default value for profile api

- go.mod
- pkg/common/defaulter/trafficmanagerprofile.go
- pkg/common/defaulter/trafficmanagerprofile_test.go
/kind feature
It can used by the default webhook or the profile controller.
Fixes #
add unit tests
> feat: create defaulter func for trafficManagerProfile

- pkg/common/objectmeta/objectmeta.go
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- pkg/controllers/hub/trafficmanagerprofile/controller_test.go
- test/common/trafficmanager/fakeprovider/endpoint.go
- test/common/trafficmanager/fakeprovider/profile.go
- test/common/trafficmanager/validator/backend.go
> feat: add traffic manager backend controller to handle delete

- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/hub/trafficmanagerprofile/suite_test.go
- test/common/trafficmanager/fakeprovider/profile.go
- test/common/trafficmanager/validator/backend.go
- test/common/trafficmanager/validator/profile.go
/kind feature
validate whether the atm profile and populate the backend status
Fixes #
> feat: validate atm profile when handling backend update

- .github/workflows/trivy.yml
/kind cleanup
The trivy action was failing from time to time due to throttling when pulling trivy image from ghcr.io registry. Thus we switch to use mcr instead.
Fixes #
Tested in the fleet repo PR: https://github.com/Azure/fleet/pull/948
> chore: fix trivy pipeline by pulling trivy image from mcr

- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/suite_test.go
> fix: fix the serviceExport integrationt test

- api/v1alpha1/trafficmanagerbackend_types.go
- charts/hub-net-controller-manager/templates/rbac.yaml
- cmd/hub-net-controller-manager/main.go
- config/crd/bases/networking.fleet.azure.com_trafficmanagerbackends.yaml
- config/rbac/role.yaml
- go.mod
- go.sum
- pkg/common/objectmeta/objectmeta.go
- pkg/common/objectmeta/objectmeta_test.go
- pkg/controllers/hub/membercluster/suite_test.go
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/member/internalmembercluster/v1alpha1/suite_test.go
- pkg/controllers/member/internalmembercluster/v1beta1/suite_test.go
- test/common/trafficmanager/fakeprovider/endpoint.go
- test/common/trafficmanager/fakeprovider/profile.go
- test/scripts/bootstrap.sh
/kind bug
Fixes #
manual test, will add the e2e tests in the future PR.
> fix: fix the atm feature related bugs

- pkg/common/objectmeta/objectmeta.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_test.go
/kind bug
- set whether the DNS label is set correctly based on the dns annotation
- requeue the request when the dns is not ready on the pip
Fixes #
> fix: requeue the request when the dns is not assigned

- docs/tutorials/BuildMultiClusterApplication/BuildMultiClusterApplication.md
> docs: fix typos

- .github/workflows/e2e-tests.yml
- test/README.md
- test/common/trafficmanager/validator/backend.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/e2e_test.go
- test/e2e/export_service_test.go
- test/e2e/framework/workload_manager.go
- test/e2e/join_test.go
- test/e2e/traffic_manager_test.go
/kind test
Add first negative e2e tests for ATM.
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/12296154911/job/34314583519 test passed
> test: add atm e2e tests

- go.mod
- go.sum
/kind bug
There is a new CVE [CVE-2024-45338](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkg.go.dev%2Fvuln%2FGO-2024-3333&data=05%7C02%7Czhiyinglin%40microsoft.com%7Cf2abf6a1b8fc4473606c08dd206339c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638702332846277008%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=MIGVZVHO8HDrdJanvb3DfMrnAGqZbjq1pT7nFXIdUEo%3D&reserved=0) published yesterday marked with HIGH severity. This CVE impacts the low-level library golang/x/net, which is again, widely used by most components that have network access.
This CVE affects the code path on the …
> fix: bump golang.org/x/net to v0.33.0 to mitigate CVE-2024-45338

- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
- test/common/trafficmanager/azureprovider/profile.go
- test/common/trafficmanager/validator/backend.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/e2e_test.go
- test/e2e/framework/workload_manager.go
- test/e2e/traffic_manager_test.go
/kind test
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/12481424602
> test: add more traffic manager e2e tests

- Makefile
- test/common/trafficmanager/azureprovider/profile.go
- test/common/trafficmanager/validator/backend.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/e2e_test.go
- test/e2e/framework/workload_manager.go
- test/e2e/traffic_manager_test.go
/kind test
add more atm e2e tests
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/12629173090
e2e tests are green
> test: add more atm e2e tests

- Makefile
/kind flake
to prevent the too many requests error and make it consistent with fleet repo
Fixes #
> chore: use the mcr image to avoid too many requests error

- pkg/common/defaulter/trafficmanagerbackend.go
- pkg/common/defaulter/trafficmanagerbackend_test.go
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/traffic_manager_test.go
/kind feature
- To support disabling the endpoint without deleting the trafficManagerBackend use case
- Fix the e2e test flakiness
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/12744560087 are green
> feat: support weight 0 for the trafficManagerBackend

- api/v1alpha1/trafficmanagerprofile_types.go
- api/v1beta1/trafficmanagerprofile_types.go
- config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml
/kind api-change
Add the resource group name to the TrafficManagerProfile
Fixes #
> feat: add the resource group name to the TrafficManagerProfile spec

- api/v1alpha1/serviceexport_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/networking.fleet.azure.com_serviceexports.yaml
- docs/tutorials/ApplicationMigration/testfiles/nginx-profile.yaml
- go.mod
- go.sum
- pkg/common/condition/condition.go
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller_test.go
- pkg/controllers/member/serviceexport/suite_test.go
- test/common/trafficmanager/fakeprovider/endpoint.go
/kind feature
Compute ATM backend weight from the serviceExport annotation
Fixes #
> feat: compute backend weight from serviceExport annotation

- .github/workflows/build-publish-mcr.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/go.yml
- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
- .github/workflows/unit-integration-tests.yml
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- go.mod
hub-net-controller-manager (gobinary)
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 0, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬──────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │        Fixed Version         │                            Title                             │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼──────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-45336 │ MEDIUM   │ fixed  │ 1.22.7            │ 1.22.11, 1.23.5, 1.24.0-rc.2 │ golang: net/http: net/http: sensitive headers incorrectly    │
│         │ …
> fix: bump go version to fix CVEs

- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_test.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/member/internalserviceexport/controller.go
- pkg/controllers/member/internalserviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/framework/workload_manager.go
- test/e2e/traffic_manager_test.go
/kind feature
- support weight 0
- fix a bug in the internalServiceExport controller
- fix the error message when the public ip is not ready
- reduce the e2e test flakiness by increasing the eventually timeout
Fixes #
> feat: support weight 0 serviceExport

- .github/workflows/e2e-tests.yml
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- test/common/trafficmanager/fakeprovider/endpoint.go
- test/common/trafficmanager/fakeprovider/profile.go
/kind bug
- retry when the agent loses the permission in the middle
- wait few mins before starting the e2e tests so that the permission assignment takes effect. https://github.com/Azure/fleet-networking/actions/runs/13297039395/job/37147419480
Fixes #
added integration tests
e2e tests are green https://github.com/Azure/fleet-networking/actions/runs/13365274390
> fix: retry when getting 4xx error

- .github/workflows/e2e-tests.yml
- Makefile
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
- test/common/trafficmanager/validator/backend.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/framework/consts.go
- test/e2e/traffic_manager_test.go
/kind test
Use separate timeout for it and e2e tests
Fixes #
> test: fix the timeout for tests

- pkg/controllers/hub/trafficmanagerbackend/suite_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerprofile/suite_test.go
- test/common/trafficmanager/fakeprovider/endpoint.go
- test/common/trafficmanager/fakeprovider/profile.go
- test/common/trafficmanager/validator/profile.go
- test/e2e/e2e_test.go
- test/e2e/traffic_manager_test.go
/kind feature
support resourceID in the profile status
Fixes #237
> feat: populate the resourceID of profile status

- pkg/common/objectmeta/objectmeta.go
- pkg/common/objectmeta/objectmeta_test.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller_test.go
- pkg/controllers/member/serviceexport/suite_test.go
/kind feature
Expose this util so that fleet repo can use it to validate the weight annotation.
Fixes #
[e2e test](https://github.com/Azure/fleet-networking/actions/runs/13715075354)
ExtractWeightFromServiceExport does not return the User error anymore, and it will depend on the caller to wrap it. So that it can avoid the loop dep.
> refactor: expose the export annotation util

- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller_test.go
- test/e2e/traffic_manager_test.go
/kind bug
fix the export condition since changing annotation won't change the generation
Fixes #
e2e tests passed, https://github.com/Azure/fleet-networking/actions/runs/13787192358
> fix: fix the export condition

- pkg/common/condition/condition.go
- pkg/common/condition/condition_test.go
- pkg/controllers/hub/internalserviceexport/controller_integration_test.go
- pkg/controllers/hub/internalserviceexport/controller_test.go
- pkg/controllers/hub/serviceimport/controller_integration_test.go
- pkg/controllers/member/internalserviceexport/controller.go
- pkg/controllers/member/internalserviceexport/controller_integration_test.go
- pkg/controllers/member/internalserviceexport/controller_test.go
- pkg/controllers/member/serviceexport/controller.go
- pkg/controllers/member/serviceexport/controller_integration_test.go
- pkg/controllers/member/serviceexport/controller_test.go
- test/e2e/export_service_test.go
- test/e2e/framework/consts.go
- test/e2e/framework/workload_manager.go
/kind bug
use the serviceExport generation instead of service
Note: service does not have the generation.
Fixes #
e2e tests passed, https://github.com/Azure/fleet-networking/actions/runs/13986059012
The change should not break the mcs or atm, and they're using serviceImport instead of serviceExport.
> fix: fix the service export condition

- .github/workflows/build-publish-mcr.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/go.yml
- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
- .github/workflows/unit-integration-tests.yml
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- go.mod
Fixing CVEs,
- CVE-2024-45336
- CVE-2024-45341
- CVE-2025-22866
> fix: bump go version to 1.23.6 for CVE

- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- test/common/trafficmanager/azureprovider/profile.go
- test/common/trafficmanager/fakeprovider/endpoint.go
- test/common/trafficmanager/fakeprovider/profile.go
- test/common/trafficmanager/validator/backend.go
- test/e2e/traffic_manager_test.go
/kind feature
populate resourceID for trafficManagerBackend status
Fixes #
e2e tests, https://github.com/Azure/fleet-networking/actions/runs/14377670818
> feat: populate resourceID for trafficManagerBackend

- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
/kind deprecation
fixed the broken trivy pipeline, https://github.com/Azure/fleet-networking/actions/runs/14512625990/job/40714583521
`This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15.`
Fixes #
> chore: fix the pipeline

- go.mod
- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
/kind feature
add status metrics for trafficManagerBackend
Fixes #
added integration tests
https://github.com/Azure/fleet-networking/actions/runs/14514674647 e2e tests passed
> feat: add status metrics for trafficManagerBackend

- api/v1beta1/trafficmanagerprofile_types.go
- config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
- test/apis/v1beta1/api_validation_integration_test.go
/kind feature
/kind api-change
Uses CEL to add kubebuilder API validation for field timeoutInSeconds within MonitorConfig in TrafficManagerProfile.
Fixes #
API validation integration test
If the IntervalInSeconds is set to 30 seconds (default), then you can set the Timeout value between 5 and 10 seconds.
If the IntervalInSeconds is set to 10 seconds, then you can set the Timeout value between 5 and 9 seconds.
As noted [here](https://github.com/Azure/fleet-networking/blob/1960b9dea70c4a658c1112ab9737a0b523829032/api/v1beta1/trafficmanagerprofile_types.go#L88C2-L91C78)
> feat: add validation for timeoutInSeconds for MonitorConfig in TrafficManagerProfile

- cmd/hub-net-controller-manager/main.go
- cmd/mcs-controller-manager/main.go
- cmd/member-net-controller-manager/main.go
/kind feature
Sets up logger for controller runtime to remove stack trace.
Fixes #
Refer to https://github.com/kubefleet-dev/kubefleet/pull/42
> feat: setup controller runtime logger

- docs/concepts/DNSBasedGlobalLoadBalancing/README.md
- docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
> docs: add atm troubleshooting doc

- docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
> docs: fix the troubleshooting doc

- docs/demos/TrafficManagerProfile/session-migrate-to-another-cluster/README.md
- docs/demos/TrafficManagerProfile/session-migrate-to-another-region/README.md
- docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
- test/e2e/traffic_manager_test.go
/kind test
Adding a webhook can blocking cx to create a duplicate trafficManagerBackend, which involves more work considering there's no validation webhook today. 
For now, we keep the implementation as it's today, and let the controller retry.
There is another rare case that customer will manually add the endpoint to the azure profile. In this case, the trafficManagerBackend will be unaccepted too.
Fixes #
added e2e tests, https://github.com/Azure/fleet-networking/actions/runs/15068110856
> test: add the tests when public ip already exists in azure profile

- .github/copilot-instructions.md
add the copilot instruction to make our agent even more smart
Fixes #
> docs: add the copilot instruction

- cmd/hub-net-controller-manager/main.go
- pkg/controllers/hub/trafficmanagerprofile/controller.go
- pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerprofile/suite_test.go
> feat: emit events for trafficManagerProfile

- .github/workflows/build-publish-mcr.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/go.yml
- .github/workflows/publish-image.yml
- .github/workflows/trivy.yml
- .github/workflows/unit-integration-tests.yml
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- go.mod
/kind fix
fix CVE-2025-4673, CVE-2025-22874, CVE-2025-0913
Fixes #
> chore: upgrade go version to 1.24.4

- docs/howtos/traffic-manager-permissions-setup.md
> docs: use hub agent role for atm feature

- pkg/controllers/hub/trafficmanagerbackend/controller.go
- pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
- pkg/controllers/hub/trafficmanagerbackend/controller_test.go
/kind bug
Reduce the traffic manager reconcile in order to reduce the arm calls
Fixes #
> feat: reduce tmb reconcile

- Makefile
- docker/hub-net-controller-manager.Dockerfile
- docker/mcs-controller-manager.Dockerfile
- docker/member-net-controller-manager.Dockerfile
- docker/net-crd-installer.Dockerfile
/kind feature
This PR updates the Dockerfiles and Makefile to enable building native ARM64 images on supported platforms. The E2E tests will use the native images if applicable.
Be sure to direct your reviewers' attention to anything that needs special consideration.
> ci: Enable arm64 native support changes

- .github/workflows/build-publish-mcr.yml
/kind feature
This PR updates the GitHub Actions pipelines to allow building ARM64/multi-arch images.
N/A
- [N/A] includes documentation
- [N/A] adds unit tests
N/A
N/A
> feat: add support for building ARM64 images
