docs/Fleet management Design.md
the draft of push model one pager
=> push model one pager

docs/Fleet management Design.md
Address comments after the design meeting
=> Flesh out the details

.pipeline/component-governance-detection.yaml
/kind bug
/kind regression
It fixes the broken component governance pipeline.
Fixes #
Will trigger a build
=> fix: fix pipeline

.github/workflows/e2e-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile
/kind bug
Fix the build image failure
Fixes #
tested locally using "make image" command
=> fix: fix go version when building the images

.github/workflows/build-publish-mcr.yml
=> fix: update mcr publishing workflow

.github/workflows/build-publish-mcr.yml, .github/workflows/e2e-tests.yml, .github/workflows/go.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml, .github/workflows/unit-integration-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile
/kind bug
https://github.com/Azure/fleet/actions/runs/9574800698/job/26398647455
Fix https://github.com/advisories/GHSA-49gw-vxvf-fc2g
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │ Title │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼────────────────────────────────────────────────────────────┤
│ stdlib │ CVE-2024-2[47](https://github.com/Azure/fleet/actions/runs/9574800698/job/26398647455#step:8:48)90 │ CRITICAL │ fixed │ 1.22.3 │ 1.21.11, 1.22.4 │ golang: net/netip: Unexpected behavior from Is …
=> chore: upgrade go version to 1.22.4

examples/getting-started/README.md, test/scripts/bootstrap.sh
=> chore: fix e2e test using eastus2 region by default

charts/mcs-controller-manager/templates/deployment.yaml, charts/mcs-controller-manager/templates/rbac.yaml, charts/member-net-controller-manager/templates/deployment.yaml, charts/member-net-controller-manager/templates/rbac.yaml
/kind cleanup
Update chart RBAC to allow refresh-token container to read secret and add log verbosity argument to member agent charts
Fixes #
=> fix: minor chart changes to install agent in upstream cluster

hack/membership/joinMC.sh
=> docs: add validation to join script

hack/membership/joinMC.sh
=> docs: fix image tag validation in script

.github/workflows/build-publish-mcr.yml, .github/workflows/e2e-tests.yml, .github/workflows/go.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml, .github/workflows/unit-integration-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile, go.mod
/kind bug
Fix the high risk CVE
hub-net-controller-manager (gobinary)
=====================================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ 1.22.4            │ 1.22.7, 1.23.1 │ encoding/gob: golang: Calling …
=> chore: bump go version to 1.22.7 to fix cve

api/v1alpha1/trafficmanagerbackend_types.go, api/v1alpha1/trafficmanagerprofile_types.go, config/crd/bases/networking.fleet.azure.com_trafficmanagerbackends.yaml, config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml, pkg/common/defaulter/trafficmanagerprofile.go, pkg/common/defaulter/trafficmanagerprofile_test.go
/kind bug
- fix the comment
- fix the crd
- add the crd validation
Fixes #
=> fix: fix the crd and defaulter

cmd/hub-net-controller-manager/main.go, pkg/controllers/hub/membercluster/controller.go
=> fix: remove error log for non-deleting MC and add v1beta1 API flag

api/v1alpha1/trafficmanagerbackend_types.go, api/v1alpha1/trafficmanagerprofile_types.go, cmd/hub-net-controller-manager/main.go, cmd/member-net-controller-manager/main.go, pkg/controllers/member/serviceexport/controller.go, pkg/controllers/member/serviceexport/controller_integration_test.go, pkg/controllers/member/serviceexport/suite_test.go
/kind feature
Add the feature flag to enable/disable atm feature.
By default, it will be turned off.
Fixes #
=> feat: add atm feature flag

api/v1alpha1/trafficmanagerbackend_types.go, api/v1alpha1/trafficmanagerprofile_types.go, pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, pkg/controllers/hub/trafficmanagerprofile/controller.go, pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go, test/common/trafficmanager/fakeprovider/endpoint.go, test/common/trafficmanager/fakeprovider/profile.go
/kind bug
- refactor the code
- add more integration tests
- fix the bug when checking the endpoint delete error
- change the Pending as Unknown reason instead of false
Fixes #
integration tests
=> fix: check the right error when deleting endpoint

pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, test/common/trafficmanager/validator/backend.go, test/common/trafficmanager/validator/profile.go
/kind feature
Fixes #
add integration tests
=> feat: handle invalid profile when handling backend update

pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, test/common/trafficmanager/fakeprovider/endpoint.go, test/common/trafficmanager/fakeprovider/profile.go
/kind feature
validate whether the service import when handling update backend
Fixes #
integration tests
updating serviceImport from invalid to valid will be tested in the future PR.
=> feat: validate service import when handling backend update

pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, pkg/controllers/hub/trafficmanagerbackend/controller_test.go, pkg/controllers/hub/trafficmanagerbackend/suite_test.go, test/common/trafficmanager/validator/backend.go
/kind feature
validate the exported services behind the serviceImport
Fixes #
IT to cover the negative cases
will add positive cases in the future PR
=> feat: validate exported services when handling backend update

examples/getting-started/artifacts/atm.yaml
Add examples for TrafficManagerProfile and TrafficManagerBackend.
Fixes #
=> docs: add trafficManagerProfile and trafficManagerBackend examples

pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, pkg/controllers/hub/trafficmanagerbackend/controller_test.go, pkg/controllers/hub/trafficmanagerbackend/suite_test.go, pkg/controllers/hub/trafficmanagerprofile/controller.go, pkg/controllers/hub/trafficmanagerprofile/controller_test.go, pkg/controllers/hub/trafficmanagerprofile/suite_test.go, test/common/trafficmanager/fakeprovider/endpoint.go, test/common/trafficmanager/fakeprovider/profile.go, test/common/trafficmanager/validator/backend.go
/kind feature
update the atm endpoints
integration tests
need to add more it in the future PR
=> feat: update atm endpoints when handling trafficmanagerbackend

.github/workflows/e2e-tests.yml, test/scripts/aks-shared-vnet.sh, test/scripts/bootstrap.sh
/kind test
Enable atm feature for the shared-vnet networking settings
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/12111480140/job/33763409219
we can support atm feature for the other networking settings in a separate PR
=> test: setup e2e tests env for atm feature

test/common/trafficmanager/validator/backend.go, test/e2e/traffic_manager_test.go
/kind bug
/kind test
/kind regression
-->
Fix the broken tests
Fixes #
=> fix: fix the main branch

api/v1alpha1/internalserviceexport_types.go, config/crd/bases/networking.fleet.azure.com_internalserviceexports.yaml
/kind bug
/kind api-change
Fix the field name incosistency
Fixes #
=> interface: fix the internalServiceExport field name

docs/tutorials/ApplicationMigration/testfiles/nginx-profile.yaml, go.mod, go.sum, pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/suite_test.go, pkg/controllers/hub/trafficmanagerprofile/controller.go, pkg/controllers/member/serviceexport/controller.go, pkg/controllers/member/serviceexport/controller_integration_test.go, pkg/controllers/member/serviceexport/controller_test.go, pkg/controllers/member/serviceexport/suite_test.go
=> Compute weight

api/v1alpha1/trafficmanagerprofile_types.go, api/v1beta1/trafficmanagerprofile_types.go, cmd/hub-net-controller-manager/main.go, config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml, pkg/common/azureerrors/azureerrors.go, pkg/common/azureerrors/azureerrors_test.go, pkg/controllers/hub/trafficmanagerbackend/controller.go, pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go, pkg/controllers/hub/trafficmanagerbackend/suite_test.go, pkg/controllers/hub/trafficmanagerprofile/controller.go, pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go, pkg/controllers/hub/trafficmanagerprofile/suite_test.go, test/apis/v1alpha1/api_validation_integration_test.go, test/apis/v1beta1/api_validation_integration_test.go, test/common/trafficmanager/fakeprovider/profile.go, test/common/trafficmanager/validator/backend.go, test/common/trafficmanager/validator/profile.go, test/e2e/e2e_test.go, test/e2e/framework/workload_manager.go, test/e2e/traffic_manager_test.go, test/scripts/bootstrap.sh
/kind feature
make the resourceGroup as required in the trafficManagerProfile
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/13195358415/job/36835542766
e2e tests are green
=> feat: support resource group in the trafficManagerProfile

cmd/hub-net-controller-manager/main.go
/kind feature
turn on the traffic manager feature
Fixes #
=> feat: turn on the traffic manager feature by default

docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile
/kind regression
fix the push mcr workflow, https://github.com/Azure/fleet-networking/actions/runs/13326277866
`ERROR: failed to solve: golang:1.22.12: failed to resolve source metadata for docker.io/library/golang:1.22.12: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/golang/manifests/sha256:1cf6c45ba39db9fd6db16922041d074a63c935556a05c5ccb62d181034df7f02: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
`
Fixes #
=> fix: fix the mcr push pipeline

cmd/member-net-controller-manager/main.go
=> fix: turn on the atm feature by default in member agent

pkg/controllers/hub/trafficmanagerbackend/suite_test.go
/kind bug
/kind test
The IT was broken because of merging #261 and #263 at the same time.
Fixes #
=> fix: fix the broken it

docs/tutorials/ApplicationMigration/testfiles/nginx-backend.yaml, docs/tutorials/ApplicationMigration/testfiles/nginx-profile.yaml, docs/tutorials/BuildMultiClusterApplication/testfiles/nginx-backend.yaml, docs/tutorials/BuildMultiClusterApplication/testfiles/nginx-profile.yaml
=> docs: use the v1beta1 ATM APIs

pkg/common/condition/condition_test.go, pkg/controllers/member/serviceexport/controller.go, pkg/controllers/member/serviceexport/controller_integration_test.go
/kind test
Add some missing tests
Fixes #
=> test: add the follow up tests and minor fix

.github/workflows/build-publish-mcr.yml, .github/workflows/e2e-tests.yml, .github/workflows/go.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml, .github/workflows/unit-integration-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, go.mod
/kind bug
https://github.com/Azure/fleet-networking/actions/runs/13914527392/job/38935068392
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ v1.23.0           │ 1.22.7, 1.23.1 │ encoding/gob: golang: Calling Decoder.Decode on a message │
│         │ …
=> fix: bump go version to fix cve

docker/member-net-controller-manager.Dockerfile
/kind bug
fix the image build failure
Fixes #
=> fix: update the go version in member agent

pkg/controllers/hub/trafficmanagerprofile/controller.go, pkg/controllers/hub/trafficmanagerprofile/controller_test.go, test/common/trafficmanager/validator/profile.go, test/e2e/traffic_manager_test.go, test/scripts/bootstrap.sh
/kind bug
- overwrite the managed fields and not touch other fields
Fixes #
added e2e tests, https://github.com/Azure/fleet-networking/actions/runs/13783243009
=> fix: build the azure profile request based on the current one

docs/concepts/DNSBasedGlobalLoadBalancing/README.md, docs/concepts/ExportingService/README.md, examples/getting-started/README.md
=> docs: add concept doc

.github/workflows/build-publish-mcr.yml, .github/workflows/e2e-tests.yml, .github/workflows/go.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml, .github/workflows/unit-integration-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile, go.mod
=> chore: fix CVE-2025-22871

.github/workflows/e2e-tests.yml, Makefile, test/scripts/collect-logs.sh
/kind feature
Fixes #
https://github.com/Azure/fleet-networking/actions/runs/16486992184
please check the e2e workflow
=> chore: collect agent logs for e2e tests

docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile, docker/net-crd-installer.Dockerfile
Fixes #
E2E run with current changes https://github.com/Azure/fleet-networking/actions/runs/16841795712/job/47714303736
=> chore: use distroless images from MCR

.github/workflows/build-publish-mcr.yml, .github/workflows/e2e-tests.yml, .github/workflows/go.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml, .github/workflows/unit-integration-tests.yml, docker/hub-net-controller-manager.Dockerfile, docker/mcs-controller-manager.Dockerfile, docker/member-net-controller-manager.Dockerfile, docker/net-crd-installer.Dockerfile, go.mod
/kind bug
fix CVE-2025-47907
Fixes #328 
=> chore: upgrade go version to 1.24.6

test/common/trafficmanager/validator/backend.go
The test util will be used by the longhaul test.
Fixes #
e2e test https://github.com/Azure/fleet-networking/actions/runs/17260172888
=> refactor: refactor the test util func
